/**
 * Intelligent Data Pipeline - Real-time Simulation Engine (React Edition)
 *
 * Live traffic is generated by faithful JavaScript ports of the three Python pipeline modules:
 *   - traffic_generator.py  →  generateEvent()
 *   - classifier.py         →  softmax() + classify()
 *   - decision_engine.py    →  DecisionEngine class
 *
 * Models a high-throughput streaming architecture with 3-tier priority queues,
 * adaptive micro-batching, backpressure, and load-shedding safeguards.
 */

// ============================================================
// PORT OF: data_pipeline/traffic_generator.py
// ============================================================

const EVENT_TYPES = ['payment', 'activity', 'auth', 'order', 'log', 'inventory'];

const INDIAN_REGIONS = [
  'mumbai', 'delhi', 'bangalore', 'hyderabad', 'chennai',
  'pune', 'kolkata', 'ahmedabad', 'jaipur', 'lucknow',
  'surat', 'kochi', 'indore', 'chandigarh', 'nagpur',
];

function randUniform(min, max) {
  return Math.random() * (max - min) + min;
}

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function choice(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Generates one raw event — direct port of traffic_generator.generate_event()
 */
function generateEvent() {
  const event_type = choice(EVENT_TYPES);

  const customer_value = Math.round(randUniform(0.05, 1.00) * 100) / 100;

  // Transaction value by type
  let transaction_value;
  if (event_type === 'payment') {
    transaction_value = randUniform(100, 100000);
  } else if (event_type === 'order') {
    transaction_value = randUniform(300, 50000);
  } else if (event_type === 'inventory') {
    transaction_value = randUniform(500, 25000);
  } else if (event_type === 'auth') {
    transaction_value = 0;
  } else if (event_type === 'activity') {
    transaction_value = randUniform(0, 5000);
  } else {
    // log
    transaction_value = 0;
  }

  // Processing cost by type
  let processing_cost;
  if (event_type === 'payment' || event_type === 'order') {
    processing_cost = randUniform(0.50, 1.00);
  } else if (event_type === 'auth') {
    processing_cost = randUniform(0.20, 0.60);
  } else if (event_type === 'inventory') {
    processing_cost = randUniform(0.30, 0.80);
  } else if (event_type === 'activity') {
    processing_cost = randUniform(0.10, 0.50);
  } else {
    // log
    processing_cost = randUniform(0.05, 0.30);
  }

  // Data size in MB by type
  let data_size;
  if (event_type === 'payment' || event_type === 'order') {
    data_size = randUniform(1.0, 10.0);
  } else if (event_type === 'inventory') {
    data_size = randUniform(1.0, 8.0);
  } else if (event_type === 'auth') {
    data_size = randUniform(0.2, 2.0);
  } else if (event_type === 'activity') {
    data_size = randUniform(0.1, 5.0);
  } else {
    // log
    data_size = randUniform(0.05, 2.0);
  }

  return {
    event_id: `evt_${randInt(100000, 999999)}`,
    event_type,
    timestamp: Math.floor(Date.now() / 1000),
    customer_value,
    transaction_value: Math.round(transaction_value * 100) / 100,
    processing_cost: Math.round(processing_cost * 100) / 100,
    data_size: Math.round(data_size * 100) / 100,
    region: choice(INDIAN_REGIONS),
  };
}

// ============================================================
// PORT OF: data_pipeline/classifier.py
// ============================================================

// [event_type]: [critical_weight, medium_weight, low_weight]
// 'auth' is not in the original BASE_WEIGHTS dict; mapped to 'activity' weights
// as auth has similar characteristics (low transaction value, small data).
const BASE_WEIGHTS = {
  payment:   [4.0,  0.5,  -2.0],
  order:     [3.5,  0.5,  -1.5],
  inventory: [0.5,  2.0,  -0.5],
  activity:  [-1.0, 1.0,   2.0],
  log:       [-2.0, 0.0,   3.0],
  auth:      [-1.0, 1.0,   2.0],  // mapped to activity weights
};

function softmax(scores) {
  const m = Math.max(...scores);
  const exps = scores.map(s => Math.exp(s - m));
  const total = exps.reduce((a, b) => a + b, 0);
  return exps.map(e => e / total);
}

/**
 * Classifies one event — direct port of classifier.classify()
 * Returns the event enriched with: priority, priority_probability, confidence
 */
function classify(event) {
  const et = event.event_type;
  const [base_c, base_m, base_l] = BASE_WEIGHTS[et] || BASE_WEIGHTS['activity'];

  const txn_norm = Math.min(event.transaction_value / 50000, 1.0);
  const cust = event.customer_value;
  const size = event.data_size;

  const critical_score = base_c + 2.0 * txn_norm + 1.5 * cust;
  const medium_score   = base_m + 0.2 * size;
  const low_score      = base_l + 0.4 * size - 0.5 * cust;

  const probs = softmax([critical_score, medium_score, low_score]);
  const labels = ['critical', 'medium', 'low'];
  const prob_map = {};
  labels.forEach((label, i) => { prob_map[label] = Math.round(probs[i] * 10000) / 10000; });

  const priority = labels.reduce((best, l) => prob_map[l] > prob_map[best] ? l : best, labels[0]).toUpperCase();
  const confidence = prob_map[priority.toLowerCase()];

  return {
    ...event,
    priority,
    priority_probability: prob_map,
    confidence,
  };
}

// ============================================================
// PORT OF: data_pipeline/decision_engine.py → DecisionEngine
// ============================================================

// Queue depth thresholds per tier (tunable) — exact copy from decision_engine.py
const QUEUE_THRESHOLDS = {
  critical: { backpressure: 500 },
  medium:   { batch: 50,  defer: 300 },
  low:      { batch: 20,  defer: 100, shed: 400 },
};

// Simulated worker drain rate per tier — exact copy from decision_engine.py
const DRAIN_RATE = {
  critical: 1.0,
  medium:   0.6,
  low:      0.3,
};

/**
 * Stateful decision engine — direct port of decision_engine.DecisionEngine
 */
class DecisionEngine {
  constructor() {
    this.queue_depth = { critical: 0.0, medium: 0.0, low: 0.0 };
  }

  reset() {
    this.queue_depth = { critical: 0.0, medium: 0.0, low: 0.0 };
  }

  /**
   * Applies backpressure / load-shedding logic.
   * Direct port of decision_engine.DecisionEngine.decide()
   */
  decide(event) {
    const tier = event.priority.toLowerCase();
    this.queue_depth[tier] = Math.max(0.0, this.queue_depth[tier] + 1 - DRAIN_RATE[tier]);
    const depth = this.queue_depth[tier];

    let action, reason;

    if (tier === 'critical') {
      action = 'STREAM';
      reason = `critical priority, always streamed (queue depth ${depth.toFixed(1)})`;
      if (depth > QUEUE_THRESHOLDS.critical.backpressure) {
        reason = `critical priority, backpressure signaled upstream, still streamed (queue depth ${depth.toFixed(1)})`;
      }

    } else if (tier === 'medium') {
      const th = QUEUE_THRESHOLDS.medium;
      if (depth < th.batch) {
        action = 'STREAM'; reason = `medium priority, queue depth ${depth.toFixed(1)} below batch threshold`;
      } else if (depth < th.defer) {
        action = 'BATCH';  reason = `medium priority, micro-batching (queue depth ${depth.toFixed(1)})`;
      } else {
        action = 'DEFER';  reason = `medium priority, deferred under high load (queue depth ${depth.toFixed(1)})`;
      }

    } else {
      // low
      const th = QUEUE_THRESHOLDS.low;
      if (depth < th.batch) {
        action = 'STREAM'; reason = `low priority, queue depth ${depth.toFixed(1)} below batch threshold`;
      } else if (depth < th.defer) {
        action = 'BATCH';  reason = `low priority, micro-batching (queue depth ${depth.toFixed(1)})`;
      } else if (depth < th.shed) {
        action = 'DEFER';  reason = `low priority, deferred under high load (queue depth ${depth.toFixed(1)})`;
      } else {
        action = 'SHED';   reason = `low priority, shed under extreme load (queue depth ${depth.toFixed(1)})`;
      }
    }

    return {
      ...event,
      queue_depth_at_decision: Math.round(depth * 100) / 100,
      action,
      decision_reason: reason,
    };
  }
}

// ============================================================
// UI HELPERS — map Python pipeline output → dashboard display fields
// ============================================================

// Python event_type → display label used in the dashboard
const EVENT_TYPE_DISPLAY = {
  payment:   'Payment',
  order:     'Order',
  inventory: 'Inventory',
  activity:  'Click',
  log:       'Log',
  auth:      'Auth',
};

// Python event_type → stats bucket used for eventsByType
const EVENT_TYPE_BUCKET = {
  payment:   'Payment',
  order:     'Order',
  inventory: 'Inventory',
  activity:  'Clicks',
  log:       'Logs',
  auth:      'Clicks',  // auth counted alongside activity/clicks
};

// action → latency string (approximate, consistent with original simulator feel)
function latencyString(action, priority, isSpikeActive) {
  if (action === 'SHED') return '—';
  if (priority === 'CRITICAL') {
    return (38 + Math.floor(Math.random() * 18)) + 'ms';
  }
  if (action === 'STREAM') {
    if (priority === 'MEDIUM') return (60 + Math.floor(Math.random() * 30)) + 'ms';
    return (110 + Math.floor(Math.random() * 80)) + 'ms';
  }
  if (action === 'BATCH') {
    if (priority === 'MEDIUM') return (120 + Math.floor(Math.random() * 180)) + 'ms';
    if (isSpikeActive) return (1.2 + Math.random() * 1.8).toFixed(1) + 's';
    return (400 + Math.floor(Math.random() * 600)) + 'ms';
  }
  if (action === 'DEFER') {
    return (1.0 + Math.random() * 1.5).toFixed(1) + 's';
  }
  return '—';
}

function actionStatus(action) {
  if (action === 'STREAM') return 'SUCCESS';
  if (action === 'BATCH')  return 'BATCHED';
  if (action === 'DEFER')  return 'DEFERRED';
  if (action === 'SHED')   return 'SHED';
  return action;
}

// ============================================================
// PIPELINE SIMULATOR — orchestrates the live pipeline
// ============================================================

export class PipelineSimulator {
  constructor() {
    this._decisionEngine = new DecisionEngine();
    this.reset();
  }

  reset() {
    this.isPaused = false;
    this.isSpikeActive = false;
    this.spikeTimestamp = null;
    this.startTime = Date.now();

    // Target arrival rate (events per second)
    // Normal: 1,000/min ≈ 16.67/s; Spike: 20,000/min ≈ 333.33/s
    this.targetRate = 16.67;
    this.actualIncomingRate = 16.7;
    this.processedRate = 16.5;
    this.processingCapacity = 40.0; // scales adaptively

    // Current State: 'NORMAL' | 'PRESSURE' | 'OVERLOAD' | 'EXTREME'
    this.systemMode = 'NORMAL';
    this.modeDescription = 'Processing events individually via direct stream channels';

    // Priority Queues — display state (synced from DecisionEngine queue_depth each tick)
    this.queues = {
      critical: {
        depth: 2,
        maxSafe: 50,
        rate: 3.3,
        p50: 38,
        p95: 52,
        types: ['Payment', 'Order'],
        status: 'PROTECTED',
        workers: 16,
      },
      medium: {
        depth: 5,
        maxSafe: 200,
        rate: 3.0,
        p50: 65,
        p95: 98,
        types: ['Inventory'],
        status: 'STREAMING',
        workers: 8,
      },
      low: {
        depth: 12,
        maxSafe: 1000,
        rate: 10.2,
        p50: 120,
        p95: 220,
        types: ['Clicks', 'Logs'],
        status: 'STREAMING',
        workers: 8,
      },
    };

    // Global Counters
    this.stats = {
      totalReceived: 0,
      totalProcessed: 0,
      totalBatched: 0,
      totalShed: 0,
      paymentsDropped: 0,
      ordersDropped: 0,
      clicksShed: 0,
      logsShed: 0,
      activeBatches: 0,
      batchSize: 1,
      avgBatchSize: 1,
      batchEfficiency: '0%',
      workerUtilization: 28,
      queueUtilization: 4,
      eventsByType: {
        Payment: 0,
        Order: 0,
        Inventory: 0,
        Clicks: 0,
        Logs: 0,
      },
      eventsByStrategy: {
        Streamed: 0,
        Batched: 0,
        Deferred: 0,
        Shed: 0,
      },
    };

    // Live Feed (ring buffer of last 40 events)
    this.liveEvents = [];

    // Time-series history for charts (40 data points)
    this.history = {
      labels: [],
      incoming: [],
      processed: [],
      capacity: [],
      latencyCritical: [],
      latencyMedium: [],
      latencyLow: [],
    };

    // Naive baseline comparison stats
    this.naive = {
      criticalP95: 55,
      throughput: 16.5,
      queueDepth: 19,
      eventsShed: 0,
      criticalDropped: 0,
    };

    // Reset the stateful decision engine queues
    this._decisionEngine.reset();

    // Pre-seed historical data points
    const now = Date.now();
    for (let i = 30; i >= 0; i--) {
      const t = new Date(now - i * 1000);
      const timeStr = t.toLocaleTimeString('en-US', { hour12: false, minute: '2-digit', second: '2-digit' });
      this.history.labels.push(timeStr);
      this.history.incoming.push(16.7 + (Math.random() * 2 - 1));
      this.history.processed.push(16.5 + (Math.random() * 2 - 1));
      this.history.capacity.push(40);
      this.history.latencyCritical.push(48 + Math.floor(Math.random() * 8));
      this.history.latencyMedium.push(75 + Math.floor(Math.random() * 15));
      this.history.latencyLow.push(140 + Math.floor(Math.random() * 30));
    }
  }

  setSpike(active) {
    this.isSpikeActive = active;
    if (active) {
      this.targetRate = 333.33; // 20,000/min
      this.spikeTimestamp = Date.now();
    } else {
      this.targetRate = 16.67; // 1,000/min
      this.spikeTimestamp = null;
    }
  }

  togglePause() {
    this.isPaused = !this.isPaused;
    return this.isPaused;
  }

  tick(dt = 1.0) {
    if (this.isPaused) return;

    const lerpFactor = this.isSpikeActive ? 0.6 : 0.3;
    this.actualIncomingRate = this.actualIncomingRate + (this.targetRate - this.actualIncomingRate) * lerpFactor;
    const jitter = (Math.random() - 0.5) * (this.isSpikeActive ? 15 : 1.5);
    const currentIncoming = Math.max(5, this.actualIncomingRate + jitter);

    const incomingCount = Math.round(currentIncoming * dt);
    this.stats.totalReceived += incomingCount;

    this.updateSystemMode(currentIncoming);
    this.processIngestion(incomingCount);
    this.updateWorkerProcessing(dt);
    this.updateNaiveModel(currentIncoming, dt);

    // Sync queue depths from DecisionEngine into the display queues
    const de = this._decisionEngine;
    this.queues.critical.depth = Math.round(de.queue_depth.critical);
    this.queues.medium.depth   = Math.round(de.queue_depth.medium);
    this.queues.low.depth      = Math.round(de.queue_depth.low);

    const nowStr = new Date().toLocaleTimeString('en-US', { hour12: false, minute: '2-digit', second: '2-digit' });
    this.history.labels.push(nowStr);
    this.history.incoming.push(Number(currentIncoming.toFixed(1)));
    this.history.processed.push(Number(this.processedRate.toFixed(1)));
    this.history.capacity.push(Number(this.processingCapacity.toFixed(1)));
    this.history.latencyCritical.push(this.queues.critical.p95);
    this.history.latencyMedium.push(this.queues.medium.p95);
    this.history.latencyLow.push(this.queues.low.p95);

    if (this.history.labels.length > 40) {
      this.history.labels.shift();
      this.history.incoming.shift();
      this.history.processed.shift();
      this.history.capacity.shift();
      this.history.latencyCritical.shift();
      this.history.latencyMedium.shift();
      this.history.latencyLow.shift();
    }
  }

  updateSystemMode(incomingRate) {
    if (incomingRate < 45) {
      this.systemMode = 'NORMAL';
      this.modeDescription = 'Processing events individually via direct stream channels';
      this.queues.medium.status = 'STREAMING';
      this.queues.low.status = 'STREAMING';
      this.processingCapacity = 45;
    } else if (incomingRate < 120) {
      this.systemMode = 'PRESSURE';
      this.modeDescription = 'Moderate load detected: Low-priority micro-batching activated';
      this.queues.medium.status = 'STREAMING';
      this.queues.low.status = 'BATCHING';
      this.processingCapacity = 140;
    } else if (incomingRate < 240) {
      this.systemMode = 'OVERLOAD';
      this.modeDescription = 'High pressure: Deferring low-priority telemetry, batching medium events';
      this.queues.medium.status = 'BATCHING';
      this.queues.low.status = 'DEFERRED';
      this.processingCapacity = 260;
    } else {
      this.systemMode = 'EXTREME';
      this.modeDescription = '20× Flash Spike: Load shedding discardable logs — Critical events 100% protected';
      this.queues.medium.status = 'BATCHING';
      this.queues.low.status = 'SHEDDING';
      this.processingCapacity = 340;
    }
  }

  /**
   * Live pipeline: for each event in this tick's batch, run
   *   generateEvent() → classify() → DecisionEngine.decide()
   * and update all stats from the real pipeline output.
   */
  processIngestion(count) {
    const batchEvents = [];

    for (let i = 0; i < count; i++) {
      // 1. Generate raw event (traffic_generator.py)
      const raw = generateEvent();

      // 2. Classify (classifier.py)
      const classified = classify(raw);

      // 3. Decide action (decision_engine.py)
      const decided = this._decisionEngine.decide(classified);

      const { event_type, priority, action } = decided;
      const bucket = EVENT_TYPE_BUCKET[event_type] || 'Clicks';

      // Update stats
      this.stats.eventsByType[bucket] = (this.stats.eventsByType[bucket] || 0) + 1;

      if (action === 'STREAM') {
        this.stats.eventsByStrategy.Streamed++;
        this.stats.totalProcessed++;
      } else if (action === 'BATCH') {
        this.stats.eventsByStrategy.Batched++;
        this.stats.totalBatched++;
        this.stats.totalProcessed++;
      } else if (action === 'DEFER') {
        this.stats.eventsByStrategy.Deferred++;
        this.stats.totalBatched++;
        this.stats.totalProcessed++;
      } else if (action === 'SHED') {
        this.stats.eventsByStrategy.Shed++;
        this.stats.totalShed++;
        if (event_type === 'log')  this.stats.logsShed++;
        else                       this.stats.clicksShed++;
      }

      // Collect sample for the live feed (max 20 candidates to avoid memory churn)
      if (batchEvents.length < 20 || priority === 'CRITICAL') {
        if (batchEvents.length < 20) {
          batchEvents.push({
            id: decided.event_id,
            type: EVENT_TYPE_DISPLAY[event_type] || event_type,
            priority,
            decision: action,
            time: latencyString(action, priority, this.isSpikeActive),
            status: actionStatus(action),
            confidence: decided.confidence,
            region: decided.region,
            prob: decided.priority_probability,
          });
        }
      }
    }

    // Sample a subset for live feed (at most 8 per tick, always include a critical if available)
    const sample = [];
    const critEvent = batchEvents.find(e => e.priority === 'CRITICAL');
    if (critEvent) sample.push(critEvent);

    for (let i = 0; i < Math.min(7, batchEvents.length); i++) {
      const randEvent = batchEvents[Math.floor(Math.random() * batchEvents.length)];
      if (!sample.includes(randEvent)) sample.push(randEvent);
    }

    const timeHeader =
      new Date().toLocaleTimeString('en-US', { hour12: false, minute: '2-digit', second: '2-digit' }) +
      '.' + Math.floor(Math.random() * 900 + 100);

    sample.forEach(e => {
      this.liveEvents.unshift({ ...e, timestamp: timeHeader });
    });

    if (this.liveEvents.length > 40) {
      this.liveEvents.length = 40;
    }
  }

  updateWorkerProcessing(dt) {
    if (this.systemMode === 'NORMAL') {
      this.queues.critical.p50 = 38 + Math.floor(Math.random() * 5);
      this.queues.critical.p95 = 51 + Math.floor(Math.random() * 6);

      this.queues.medium.p50 = 62 + Math.floor(Math.random() * 10);
      this.queues.medium.p95 = 95 + Math.floor(Math.random() * 12);

      this.queues.low.p50 = 110 + Math.floor(Math.random() * 20);
      this.queues.low.p95 = 210 + Math.floor(Math.random() * 30);

      this.processedRate = Math.max(14, this.actualIncomingRate - Math.random());
      this.stats.workerUtilization = 28 + Math.floor(Math.random() * 6);
      this.stats.queueUtilization = 4;
      this.stats.batchSize = 1;
      this.stats.activeBatches = 0;
      this.stats.avgBatchSize = 1;
      this.stats.batchEfficiency = '0%';

    } else if (this.systemMode === 'PRESSURE') {
      this.queues.critical.p50 = 40 + Math.floor(Math.random() * 6);
      this.queues.critical.p95 = 54 + Math.floor(Math.random() * 8);

      this.queues.medium.p50 = 90 + Math.floor(Math.random() * 20);
      this.queues.medium.p95 = 140 + Math.floor(Math.random() * 25);

      this.queues.low.p50 = 320 + Math.floor(Math.random() * 50);
      this.queues.low.p95 = 620 + Math.floor(Math.random() * 80);

      this.processedRate = this.actualIncomingRate * 0.96;
      this.stats.workerUtilization = 62 + Math.floor(Math.random() * 8);
      this.stats.queueUtilization = 22;
      this.stats.batchSize = 25;
      this.stats.activeBatches = 4;
      this.stats.avgBatchSize = 22;
      this.stats.batchEfficiency = '48%';

    } else if (this.systemMode === 'OVERLOAD') {
      this.queues.critical.p50 = 44 + Math.floor(Math.random() * 6);
      this.queues.critical.p95 = 58 + Math.floor(Math.random() * 8);

      this.queues.medium.p50 = 180 + Math.floor(Math.random() * 30);
      this.queues.medium.p95 = 290 + Math.floor(Math.random() * 40);

      this.queues.low.p50 = 950 + Math.floor(Math.random() * 120);
      this.queues.low.p95 = 1450 + Math.floor(Math.random() * 150);

      this.processedRate = this.actualIncomingRate * 0.91;
      this.stats.workerUtilization = 84 + Math.floor(Math.random() * 7);
      this.stats.queueUtilization = 54;
      this.stats.batchSize = 50;
      this.stats.activeBatches = 7;
      this.stats.avgBatchSize = 46;
      this.stats.batchEfficiency = '76%';

    } else {
      // EXTREME 20× SPIKE
      this.queues.critical.p50 = 45 + Math.floor(Math.random() * 7);
      this.queues.critical.p95 = 59 + Math.floor(Math.random() * 9);
      this.queues.critical.rate = 66.7;

      this.queues.medium.p50 = 240 + Math.floor(Math.random() * 40);
      this.queues.medium.p95 = 410 + Math.floor(Math.random() * 60);
      this.queues.medium.rate = 60.0;

      this.queues.low.p50 = 1600 + Math.floor(Math.random() * 200);
      this.queues.low.p95 = 2650 + Math.floor(Math.random() * 350);
      this.queues.low.rate = 180.0;

      this.processedRate = 310 + Math.floor(Math.random() * 20);
      this.stats.workerUtilization = 94 + Math.floor(Math.random() * 5);
      this.stats.queueUtilization = 68;
      this.stats.batchSize = 80;
      this.stats.activeBatches = 12;
      this.stats.avgBatchSize = 74;
      this.stats.batchEfficiency = '88%';
    }

    this.totalQueueDepth = this.queues.critical.depth + this.queues.medium.depth + this.queues.low.depth;
  }

  updateNaiveModel(incomingRate, dt) {
    if (!this.isSpikeActive) {
      this.naive.criticalP95 = 54 + Math.floor(Math.random() * 8);
      this.naive.throughput = this.processedRate;
      this.naive.queueDepth = 22 + Math.floor(Math.random() * 8);
      this.naive.eventsShed = 0;
      this.naive.criticalDropped = 0;
    } else {
      this.naive.criticalP95 = Math.min(14500, this.naive.criticalP95 + 450);
      this.naive.throughput = Math.min(95, this.naive.throughput + 2);
      this.naive.queueDepth = Math.min(12500, this.naive.queueDepth + 260);
      this.naive.eventsShed += Math.floor(Math.random() * 25 + 10);
      this.naive.criticalDropped += Math.floor(Math.random() * 5 + 2);
    }
  }
}
